import { useState, useEffect } from "react";
import { FileIcon, SaveIcon } from "lucide-react";

interface SimpleCodeEditorProps {
  filePath: string | null;
  onSave: (content: string) => void;
}

export default function SimpleCodeEditor({ filePath, onSave }: SimpleCodeEditorProps) {
  const [content, setContent] = useState("");
  const [isSaved, setIsSaved] = useState(true);
  const [lineCount, setLineCount] = useState(1);

  useEffect(() => {
    if (filePath) {
      loadFile(filePath);
    }
  }, [filePath]);

  useEffect(() => {
    const lines = content.split("\n").length;
    setLineCount(lines);
  }, [content]);

  const loadFile = async (path: string) => {
    // TODO: Load actual file content via Tauri
    // For now, show placeholder content
    const mockContent = getMockFileContent(path);
    setContent(mockContent);
    setIsSaved(true);
  };

  const getMockFileContent = (path: string): string => {
    if (path.endsWith(".jsx") || path.endsWith(".js")) {
      return `import React from 'react';

export default function Component() {
  return (
    <div className="container">
      <h1>Hello from ${path.split("/").pop()}</h1>
      <p>This is a placeholder. The agent will generate actual code here.</p>
    </div>
  );
}`;
    }

    if (path.endsWith(".json")) {
      return `{
  "name": "my-project",
  "version": "1.0.0",
  "description": "Generated by Software Developer Agent IDE"
}`;
    }

    if (path.endsWith(".md")) {
      return `# Project README

This file was generated by the AI agent.

## Getting Started

Instructions will be added here...`;
    }

    return `// File: ${path}\n// Content will be generated by the AI agent\n`;
  };

  const handleChange = (newContent: string) => {
    setContent(newContent);
    setIsSaved(false);
  };

  const handleSave = () => {
    onSave(content);
    setIsSaved(true);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if ((e.ctrlKey || e.metaKey) && e.key === "s") {
      e.preventDefault();
      handleSave();
    }
  };

  if (!filePath) {
    return (
      <div className="h-full flex items-center justify-center bg-background">
        <div className="text-center space-y-3">
          <FileIcon className="w-16 h-16 text-muted-foreground mx-auto opacity-50" />
          <div>
            <h3 className="text-lg font-semibold text-foreground">No File Selected</h3>
            <p className="text-sm text-muted-foreground mt-2">
              Select a file from the explorer or ask the agent to create one
            </p>
          </div>
        </div>
      </div>
    );
  }

  const fileName = filePath.split("/").pop() || "";
  const fileExtension = fileName.split(".").pop() || "";

  return (
    <div className="h-full flex flex-col bg-background">
      {/* Editor Header */}
      <div className="border-b border-border px-4 py-2 flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <FileIcon className="w-4 h-4 text-muted-foreground" />
          <span className="text-sm font-medium text-foreground">{fileName}</span>
          {!isSaved && (
            <span className="w-2 h-2 rounded-full bg-orange-500" title="Unsaved changes" />
          )}
        </div>

        <div className="flex items-center space-x-4">
          <span className="text-xs text-muted-foreground">
            {lineCount} lines
          </span>
          <button
            onClick={handleSave}
            disabled={isSaved}
            className="flex items-center space-x-1 px-3 py-1 text-xs bg-primary text-primary-foreground rounded hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            <SaveIcon className="w-3 h-3" />
            <span>{isSaved ? "Saved" : "Save"}</span>
          </button>
        </div>
      </div>

      {/* Editor Area */}
      <div className="flex-1 flex overflow-hidden">
        {/* Line Numbers */}
        <div className="w-12 bg-secondary/30 border-r border-border overflow-y-auto select-none">
          <div className="py-3 px-2 font-mono text-xs text-muted-foreground text-right space-y-[2px]">
            {Array.from({ length: lineCount }, (_, i) => (
              <div key={i + 1} className="leading-6">
                {i + 1}
              </div>
            ))}
          </div>
        </div>

        {/* Text Area */}
        <textarea
          value={content}
          onChange={(e) => handleChange(e.target.value)}
          onKeyDown={handleKeyDown}
          className="flex-1 p-3 bg-background text-foreground font-mono text-sm resize-none focus:outline-none leading-6"
          spellCheck={false}
          placeholder="Start typing or let the AI agent generate code..."
        />
      </div>

      {/* Status Bar */}
      <div className="border-t border-border px-4 py-1 flex items-center justify-between text-xs text-muted-foreground">
        <div className="flex items-center space-x-4">
          <span>UTF-8</span>
          <span>{fileExtension.toUpperCase()}</span>
        </div>
        <div className="flex items-center space-x-4">
          <span>Ln {content.split("\n").length}, Col 1</span>
          <span>💡 Monaco editor coming soon</span>
        </div>
      </div>
    </div>
  );
}
